In [11]:
import pandas as pd

print(pd.__version__)

2.3.3

In [12]:
df_2019 = pd.read_csv("data/Divvy_Trips_2019_Q1 - Divvy_Trips_2019_Q1.csv")

In [13]:
df_2020 = pd.read_csv("data/Divvy_Trips_2020_Q1 - Divvy_Trips_2020_Q1.csv")

In [15]:
df_2019.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,21742443,2019-01-01 0:04:37,2019-01-01 0:11:07,2167,390,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber,Male,1989.0
1,21742444,2019-01-01 0:08:13,2019-01-01 0:15:34,4386,441,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber,Female,1990.0
2,21742445,2019-01-01 0:13:23,2019-01-01 0:27:12,1524,829,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber,Female,1994.0
3,21742446,2019-01-01 0:13:45,2019-01-01 0:43:28,252,"1,783.00",123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber,Male,1993.0
4,21742447,2019-01-01 0:14:52,2019-01-01 0:20:56,1170,364,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber,Male,1994.0

In [18]:
df_2020.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,EACB19130B0CDA4A,docked_bike,2020-01-21 20:06:59,2020-01-21 20:14:30,Western Ave & Leland Ave,239,Clark St & Leland Ave,326.0,41.9665,-87.6884,41.9671,-87.6674,member
1,8FED874C809DC021,docked_bike,2020-01-30 14:22:39,2020-01-30 14:26:22,Clark St & Montrose Ave,234,Southport Ave & Irving Park Rd,318.0,41.9616,-87.6660,41.9542,-87.6644,member
2,789F3C21E472CA96,docked_bike,2020-01-09 19:29:26,2020-01-09 19:32:17,Broadway & Belmont Ave,296,Wilton Ave & Belmont Ave,117.0,41.9401,-87.6455,41.9402,-87.6530,member
3,C9A388DAC6ABF313,docked_bike,2020-01-06 16:17:07,2020-01-06 16:25:56,Clark St & Randolph St,51,Fairbanks Ct & Grand Ave,24.0,41.8846,-87.6319,41.8918,-87.6206,member
4,943BC3CBECCFD662,docked_bike,2020-01-30 8:37:16,2020-01-30 8:42:48,Clinton St & Lake St,66,Wells St & Hubbard St,212.0,41.8856,-87.6418,41.8899,-87.6343,member

In [19]:
df_2019.shape

(365069, 12)

In [20]:
df_2020.shape

(426887, 13)

In [21]:
df_2019.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='object')

In [22]:
df_2020.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [24]:
df_2019 = df_2019.rename(columns={
    'trip_id': 'ride_id',
    'start_time': 'started_at',
    'end_time' : 'ended_at',
    'from_station_name' : 'start_station_name',
    'from_station_id' : 'start_station_id',
    'to_station_name' : 'end_station_name',
    'to_station_id' : 'end_station_id',
    'usertype' : 'member_casual'
})

In [25]:
df_2019.columns

Index(['ride_id', 'started_at', 'ended_at', 'bikeid', 'tripduration',
       'start_station_id', 'start_station_name', 'end_station_id',
       'end_station_name', 'member_casual', 'gender', 'birthyear'],
      dtype='object')

In [26]:
df_2019['member_casual'].value_counts()

member_casual
Subscriber    341906
Customer       23163
Name: count, dtype: int64

In [27]:
df_2019['member_casual'] = df_2019['member_casual'].replace({
    'Subscriber' : 'member',
    'Customer':'casual'
})

In [55]:
 df_2019['member_casual'].value_counts()

member_casual
member    341906
casual     23163
Name: count, dtype: int64

In [29]:
df_2020['member_casual'].value_counts()

member_casual
member    378407
casual     48480
Name: count, dtype: int64

In [30]:
df_2019[['started_at', 'ended_at']].dtypes

started_at    object
ended_at      object
dtype: object

In [31]:
df_2020[['started_at','ended_at']].dtypes

started_at    object
ended_at      object
dtype: object

In [32]:
df_2019['started_at'] = pd.to_datetime(df_2019['started_at'])
df_2019['ended_at'] = pd.to_datetime(df_2019['ended_at'])

In [34]:
df_2020['started_at'] = pd.to_datetime(df_2020['started_at'])
df_2020['ended_at'] = pd.to_datetime(df_2020['ended_at'])

In [33]:
df_2019[['started_at', 'ended_at']].dtypes

started_at    datetime64[ns]
ended_at      datetime64[ns]
dtype: object

In [69]:
df_2020[['started_at', 'ended_at']].dtypes

started_at    datetime64[ns]
ended_at      datetime64[ns]
dtype: object

In [71]:
df_2019['ride_length'] = df_2019['ended_at'] - df_2019['started_at']

In [77]:
df_2019[['started_at', 'ended_at', 'ride_length']].head()

           started_at            ended_at     ride_length
0 2019-01-01 00:04:37 2019-01-01 00:11:07 0 days 00:06:30
1 2019-01-01 00:08:13 2019-01-01 00:15:34 0 days 00:07:21
2 2019-01-01 00:13:23 2019-01-01 00:27:12 0 days 00:13:49
3 2019-01-01 00:13:45 2019-01-01 00:43:28 0 days 00:29:43
4 2019-01-01 00:14:52 2019-01-01 00:20:56 0 days 00:06:04

In [76]:
df_2020['ride_length'] = df_2020['ended_at'] - df_2020['started_at']

In [79]:
df_2020[['started_at', 'ended_at', 'ride_length']].head()

  started_at ended_at ride_length
0        NaT      NaT         NaT
1        NaT      NaT         NaT
2        NaT      NaT         NaT
3        NaT      NaT         NaT
4        NaT      NaT         NaT

In [87]:
(df_2019['ride_length'] < pd.Timedelta(0)).sum()

np.int64(0)

In [90]:
(df_2020['ride_length'] < pd.Timedelta(0)).sum()

np.int64(0)

In [92]:
(df_2019['ride_length'] == pd.Timedelta(0)).sum()

np.int64(0)

In [94]:
(df_2020['ride_length'] == pd.Timedelta(0)).sum()

np.int64(0)

In [96]:
df_2020[df_2020['ride_length'] <= pd.Timedelta(0)][
    ['ride_id', 'started_at', 'ended_at', 'ride_length', 'member_casual']
].head(10)

Empty DataFrame
Columns: [ride_id, started_at, ended_at, ride_length, member_casual]
Index: []

In [99]:
df_2020 = df_2020[df_2020['ride_length'] > pd.Timedelta(0)]

In [101]:
(df_2020['ride_length'] <= pd.Timedelta(0)).sum()

np.int64(0)

In [103]:
df_2019['day_of_week'] = df_2019['started_at'].dt.dayofweek

In [105]:
df_2020['day_of_week'] = df_2020['started_at'].dt.dayofweek

In [107]:
df_2019[['started_at', 'day_of_week']].head()

           started_at  day_of_week
0 2019-01-01 00:04:37            1
1 2019-01-01 00:08:13            1
2 2019-01-01 00:13:23            1
3 2019-01-01 00:13:45            1
4 2019-01-01 00:14:52            1

In [109]:
df_2020[['started_at', 'day_of_week']].head()

Empty DataFrame
Columns: [started_at, day_of_week]
Index: []

In [111]:
df_2019.isnull().sum()

ride_id                   0
started_at                0
ended_at                  0
bikeid                    0
tripduration              0
start_station_id          0
start_station_name        0
end_station_id            0
end_station_name          0
member_casual             0
gender                19711
birthyear             18023
ride_length               0
day_of_week               0
dtype: int64